### PR TITLE
Migration to .NET 6, Implementation of mouse-scroll and desktop name notification

### LINKED ISSUE #5: Option to show Desktop Name
It would be very nice to be able to see the desktop name, somehow.

Suggestion for how it could be shown, in order of (my) preference:

- As an on screen tooltip/toast/notification when you switch desktop, which goes away on it's own in a second or two
- In the taskbar: desktop number - desktop name, or just desktop name
- as a tooltip on hover of the taskbar icon

Thanks for the super useful virtualdesktop indicator - makes virtual desktops on windows much more useable!

### LINKED ISSUE #6: Scrollwheel on icons to switch desktop
Would be great if you could use the mouse scrollwheel on the icon to switch/scroll desktops left/right.

### LINKED ISSUE #8: Click icon to show the Task View screen
If clicking the virtualdesktop-indicator button did the same a clicking the Task View button - i.e. showed the built in Task View screen, then I could hide the Task View button and just have one desktop management button on the taskbar instead of two.

### PR DESCRIPTION
**Pull request by Flaflo**
:building_construction: Migration to .NET 6
:recycle: Restructured and cleaned the whole project
:sparkles: Implemented opening TaskView on click, closes #8 
:sparkles: Implemented mouse scroll over icon will switch desktops, closes #6
:sparkles: Implemented notification toast with desktop name when switching virtual desktops, closes #5

### CODE REVIEW

**Comment by Flaflo** [comment]
Sorry, everything is squashed into one commit, but I had no choice after I restructured the project containing the POCs I made.
Hope this is okay!

**Comment by Flaflo** [comment]
@zgdump I think this PR can be merged now. If you want, I can do the settings page aswell and merge #3

**Comment by zgdump** [comment]
@Flaflo, thanks for PR! I tested it and found some bugs

1. The right mouse button does not work. When clicked, the task view is displayed
I once added the task view opening by clicking on the icon. But I could not solve the problem with closing the task view on the second click. If you find it, look in the commit history

2. The notification window is displayed on the task view

image

3. If move the mouse between desktops very often, then there are a lot of windows, and then the explorer falls

image

**Comment by zgdump** [comment]
Additionally, I could not test the change of desktops by scrolling. It didn't work on my touchpad. Or I'm doing something wrong)

**Comment by zgdump** [comment]
@Flaflo In addition to bugs, I do not approve of migrating to .net 6. It still does not come as part of Windows. This is an extra dependency that must be installed by the user. What are the benefits of migration?

**Comment by Flaflo** [comment]
> @Flaflo In addition to bugs, I do not approve of migrating to .net 6. It still does not come as part of Windows. This is an extra dependency that must be installed by the user. What are the benefits of migration?

Benefits would be futureproofness, because .net framework will not be supported forever. Access to the latest C# features. There is an option to create a standalone exe using AOT or packing the .net runtime inside the exe.

Of course the migration is not mandatory but I would highly recommend it.

**Comment by Flaflo** [comment]
> Additionally, I could not test the change of desktops by scrolling. It didn't work on my touchpad. Or I'm doing something wrong)

I am unfortunately not able to test this.

**Comment by zgdump** [comment]
@Flaflo thanks, bugs fixed. There is still the oddity that sometimes a context menu and a pop-up window appear under the taskbar. But I don't think it's a bug of your code

**Comment by zgdump** [comment]
What do you think if we try to integrate this utility into PowerToys?) Implement colors, windows 11 like settings, restyle the pop-up as new sound dialog. It's partly overengineering, but...

**Comment by Flaflo** [comment]
> @Flaflo thanks, bugs fixed. There is still the oddity that sometimes a context menu and a pop-up window appear under the taskbar. But I don't think it's a bug of your code

I also noticed this. Looks like a bug with the .net framework and how it registers notification icons. I tried creating a fully native context menu using winapi (TrackPopupMenuEx) and it was the same bug.

I dont know if this is a quirk with .net 6 or a bug introduced with a recent windows version...

**Comment by zgdump** [comment]
> I dont know if this is a quirk with .net 6 or a bug introduced with a recent windows version...

Don't worry. This mistake is 20 years old. It just always pops up in different ways, according to the mood 😁

**Comment by Flaflo** [comment]
> What do you think if we try to integrate this utility into PowerToys?) Implement colors, windows 11 like settings, restyle the pop-up as new sound dialog. It's partly overengineering, but...

Maybe we should continue this conversation somewhere else, do you have a way I can contact you outside github?

**Comment by zgdump** [comment]
> Maybe we should continue this conversation somewhere else, do you have a way I can contact you outside github?

Yes, my telegram `@zgdump`

**Comment by zgdump** [comment]
Should I accept PR?

**Comment by Flaflo** [comment]
> Should I accept PR?

Depends if you want me to roll back to .net framework or do we stay with .net 6?

**Comment by zgdump** [comment]
> Depends if you want me to roll back to .net framework or do we stay with .net 6?

Let this remain

**Comment by zgdump** [comment]
Go

**Pull request merged**
